### ISSUE TITLE
Anthology Ally not working within course sections Moodle 4.4

### ISSUE THREAD

**Issue by RayCoSector** [anthology-ally/moodle-filter_ally#83]
Hello,

We've spotted the following if the user is on a course URL which contains **section.php** then Ally icons do not appear.

section pages exist on the following course formats which we use : Custom, Weekly & Grid format

We are using:
Moodle 4.4.5
filter_ally 2024112200
tool_ally 2024112200
report_allylti 2024112200

Here is an fake example URL for the type of pages which are affected
www.your-moodle-site.com/course/section.php?id=1000

When on the main page of a course using Weekly format, you see this as expected :
![Image](https://github.com/user-attachments/assets/3df470e6-16aa-4cd2-8d0e-64d51f1c28bf)

When in the section page within the same course, nothing shows :
![Image](https://github.com/user-attachments/assets/771320fb-9084-49f2-9edb-5cb9d941fd00)

Using Weekly as an example as it is a core course format.

Could someone please take a look and let us know asap, when using Grid format this means that students can not see an Ally icons at all as each page section is within section.php so this is a major issue for our institution. 

We are deploying the following latest available 4.4 plugin versions to prod shortly - should it have been fixed in there, the release notes do not say what has been fixed - this is not at all useful - could these be updated in future or a page created somewhere to tell us what has been fixed ?

filter_ally 2025030300
tool_ally 2025021900
report_allylti 2024112200

Many thanks,
Ray Reid.

**Comment by jhopkins77** [comment]
Hello, Everyone. I work at Bryn Mawr College in Pennsylvania as part of the team that manages Moodle. We upgraded to version 4.4.3 last week and the Ally icons subsequently disappeared on all courses. This is true for courses using the Weekly Format and the Customs format, like in the original post from @RayCoSector (we don't have Grid format enabled). Furthermore, this is also happening on pages (e.g., "Home"). We think this is ultimately an Ally issue and have been working with their support team, but we've yet to find a solution. Has anyone here made any progress?

In case anyone wants information on our Moodle install, here it its:
- Version: 4.4.3
- Theme: BMC Boosted, our own slight modification of the Boost theme (default.scss)
- filter_ally: 2025030300
- tool_ally: 2025021900
- report_allylti: 2024112200

Also, here's an example of the missing icons: 

<img width="781" alt="Image" src="https://github.com/user-attachments/assets/6bf45df0-916d-49bc-8913-56a28501c180" />

**Comment by RayCoSector** [comment]
Thanks @jhopkins77 very useful information, we were holding out that upgrading the latest plugins (which was scheduled in for tomorrow morning) would fix it.. Since you are already using these I'd say that'll be a no.

We too have been trying to raise this with Blackboard. We have 16,000+ courses using course formats which are not working !

Do the Blackboard Ally icons show for you when in edit mode ?

Regards,
Ray.

**Comment by jhopkins77** [comment]
Hello, @RayCoSector. Thanks for the response! Perhaps upgrading the plugin will, when combined with Moodle 4.4.5, produce the perfect blend to get icons working again. As you said though, that's probably not the most likely outcome. 

To you question, no, icons do not appear when we move to edit mode. Could you let me know some things about your Moodle site?:
-Does Ally's reporting feature still work for you?
-Do you do anything to customize your version of Boost Union?
-Is your site still making calls to Ally when pages are loading (the rep we've been speaking with asked us to look into this—call are not being made).

**Comment by RayCoSector** [comment]
Morning @jhopkins77 after the update our site is in the same state as yours. Ally is not working at all !

We are trying to escalate this with their customer support !

Not good :(

**Comment by jhopkins77** [comment]
Hello Ray,

Sorry to hear that. At least we're no longer alone in our frustration 😆. Regardless, let us know if you figure out anything while working with Ally support. I'll do the same. 

Best,
Jeff

**Comment by leonstr** [comment]
It should be possible to fix this by:

1. Copying [this file](https://github.com/leonstr/moodle-filter_ally/blob/68-inclusiondeprecated/filter.php) to `filter/ally/filter.php`.

2. Editing file `filter/ally/classes/text_filter.php` changing line 49 to:

```
class text_filter extends \moodle_text_filter {

```

(This is frustrating since we supplied [a patch to support both Moodle 4.4 and 4.5 in November 2024](https://github.com/anthology-ally/moodle-filter_ally/pull/72) which was ignored, the maintainers instead released a similar update but which broke 4.4 compatibility).

**Comment by RayCoSector** [comment]
Thanks @leonstr I've done as you said on our UAT site and can see the icons have returned to courses - but not when you are in a section.php page 

/course/view.php?id=113118
![Image](https://github.com/user-attachments/assets/a976759a-7c48-40fd-aba7-74cdf9874693)

/course/section.php?id=1844692
![Image](https://github.com/user-attachments/assets/98309eb1-f27c-4de3-872a-b0107b57f69d)

You dont happen to have a fix for this as well do you ?

Many thanks,
Ray Reid.

**Comment by leonstr** [comment]
@RayCoSector I think you've got a slightly older filter_ally version:

> filter_ally: 2024112200

This is fixed version 2025030300 (obviously this contains the changes that break in Moodle 4.4.).

The fix is just this one-line change in [commit 8450058](https://github.com/anthology-ally/moodle-filter_ally/commit/84500585de390e0b233cc6787d8051042c6efb53).

**Comment by RayCoSector** [comment]
Hi @leonstr we've got filter_ally version 4.4.3 2025030300 on both our UAT and Prod site now, different to what I said in the opening message (Ally customer support told us for them to help them we needed to be on the latest) 

Adding both fixes that you mentioned today has got our UAT site fully working again.. many thanks for this.

We're trying to push Ally customer support to release a version with both of these fixes in it, as I don't really want to be changing files and adding new ones to our customers production site, when it should really becoming direct from Ally!

Thanks again,
Ray.

**Comment by RayCoSector** [comment]
@jhopkins77 the latest release dropped 19 hours ago [4.4.4 (2025031800)](https://moodle.org/plugins/filter_ally/versions)

We weren't told about it, it just magically appeared.

@leonstr part of your mentioned fixes have made it, but the extra file filter.php is still not in there, I added it after seeing that it still does not work - but that then breaks the whole site !

![Image](https://github.com/user-attachments/assets/518177e6-a1c4-4c78-8359-8e6ca1f199a4)

We've just heard from the support team that their QA team are working on verifying the fix. Not sure why a further broken version made Moodle plugins 20 hrs ago.

Regards,
Ray.

**Comment by jhopkins77** [comment]
Hey, @RayCoSector. Thanks for the heads-up. I was looking at the "plugins overview" page within our Moodle instances. I suppose the update hasn't filtered down to individual instances yet. 

Either way, it's frustrating that we weren't informed about the update either, which we were promised would happen on yesterday's call. Then again, if the update isn't truly ready for prime time, they perhaps don't want to shine a light on it. Whatever the case, none of this is ideal.

**Comment by gthomas2** [comment]
The 4.5 code that was accidentally merged into the MOODLE_404_STABLE branch has now been removed.

**Comment by RayCoSector** [comment]
Thanks @gthomas2 we have this set for deployment ([2025031900](https://moodle.org/plugins/filter_ally/versions)) at 2pm UK time to see if it fixes the issues - will report back after that.

**Comment by RayCoSector** [comment]
Hello all, we've deployed ([2025031900](https://moodle.org/plugins/filter_ally/versions)) slightly earlier than planned and happy to report that Ally is working as expected.

Thanks all,

Regards,
Ray.

**Comment by leonstr** [comment]
@gthomas2 This fix has reintroduced the _Inclusion of filters ... has been deprecated_ warning with Moodle 4.5 (i.e. issue #68). In our unmerged patch in PR #72 we deliberately [maintained error-free compatibility with 4.4 and 4.5](https://moodle.org/mod/forum/discuss.php?d=463370).

E.g. testing with filter_ally 2025031900 downloaded from the plugins directory and Moodle 4.5.3+ (Build: 20250318):

```
# vendor/bin/phpunit --filter filter_ally
⋮
There were 6 errors:

1) filter_ally\filter_test::test_filter_img
Unexpected debugging() call detected.
Debugging: Inclusion of filters from 'filter/ally/filter.php' using the 'filter_ally' class naming has been deprecated. Please rename your class to \filter_ally\text_filter and move it to 'filter/ally/classes/text_filter.php'. See MDL-82427 for more information.
⋮
ERRORS!
Tests: 33, Assertions: 259, Errors: 6.
```

With filter_ally 2025031800: `OK (33 tests, 259 assertions)`.

**Comment by gthomas2** [comment]
@RayCoSector thanks for reporting back, I'm pleased it is now working as expected. Apologies that we didn't trap the section bug. I will create a behat tests for that to prevent future regressions.

**Comment by gthomas2** [comment]
@leonstr - "This fix has reintroduced the Inclusion of filters ... has been deprecated warning with Moodle 4.5" there isn't an official version of Moodle 4.5 yet.  The PR that was merged yesterday was for MOODLE_404_STABLE. If you are wanting to use Ally with Moodle 4.5 then the master branch is probably a better bet, although I have to stress that a MOODLE_405_STABLE release is not available yet but will be soon.

**Comment by leonstr** [comment]
@gthomas2 Thanks, I'm doing my best to be accurate with [the available information](https://moodle.org/plugins/filter_ally/versions):

![Image](https://github.com/user-attachments/assets/7599c88d-e787-447f-b54c-4a5fd23d2588)

**Comment by gthomas2** [comment]
@leonstr I'll ask the relevant people how that happened. Thanks for posting the screenshot

**Comment by jhopkins77** [comment]
Hello, @gthomas2 (and everyone else too). Just wanted to confirm that we deployed the new version of the Ally plugin to our main Moodle this morning and it has successfully solved our problems. Thank you again for your work addressing this issue. Particularly in light of the criticism I was offering earlier, it's really appreciated. 

If we can tie a bow on all this, what exactly was causing this issue and what did you do to fix it? Based on [this comment from @leonstr](https://github.com/anthology-ally/moodle-filter_ally/issues/83#issuecomment-2735954860) it seems like the issue was with how filters were set up, but I want to be sure I'm understanding just in case something like this pops up in the future. Thanks in advance for any and all help!

**Comment by aspark21** [comment]
Is there an update on when there will be a 4.5 version?

Anthology really needs to get it's act together and have updated versions within weeks of a new major Moodle version being released.

**Comment by gthomas2** [comment]
@jhopkins77  the issue with 4.4 was due to the sections URL changing. We had to modify a regex for checking that the current page is a course page. To ensure this bug doesn't happen in future I have added a new behat test.

**Comment by gthomas2** [comment]
@aspark21 I have completed a 4.5 version but haven't tested it yet. And to address your concern about future versions, the plan is to have the next version in master as a preview when stable releases are cut

**Comment by jhopkins77** [comment]
Hello, @gthomas2. I literally went on parental leave the day you answered my question, so forgive my belated thanks. Still, your providing this information is much appreciated! 

As next steps, my team is now discussing what upgrade we'll do over the summer. To echo @aspark21, do we have any update on a 4.5 release? Furthermore, do you have any sense of when a Moodle 5 version will be released?

Thanks again for your help! It's clear you're juggling a lot with these upgrades, so your work and updates are appreciated.

**Comment by gthomas2** [comment]
@jhopkins77 No problem, sorry for my late reply too. I've just been waiting for a branch to be cut off of master for MOODLE_405_STABLE. This is available now but unfortunately it has been incorrectly named as MOODLE_4O5_STABLE with a letter O where the zero should be. I'll let the Ally team know about this.

**Comment by gthomas2** [comment]
@jhopkins77 I have run behat tests against 5 and got them all to pass. I can't remember if I had to change anything. I'll try to get a WIP branch up soon .

**Comment by jhopkins77** [comment]
Hello, @gthomas2. That would be amazing! Let me know if there's anything I can do to help. Otherwise, just give a holler when the branch is up. Thank you again for everything!
